/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

/**
 *
 * @author ADM
 */
public class Trabajo extends javax.swing.JFrame {

    /**
     * Creates new form Trabajo
     */
    public Trabajo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icono = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lunes = new javax.swing.JButton();
        Martes = new javax.swing.JButton();
        Miercoles = new javax.swing.JButton();
        Jueves = new javax.swing.JButton();
        Viernes = new javax.swing.JButton();
        Sabado = new javax.swing.JButton();
        Domingo = new javax.swing.JButton();
        linea_azul = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        btn_Lavar_ya = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono negro2.jpg"))); // NOI18N
        Icono.setText("jLabel1");
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 210));

        Bienvenido.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText("¡ Bienvenido !");
        Bienvenido.setToolTipText("");
        getContentPane().add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 230, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione el dia que desea");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("hacer reservacion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        Lunes.setBackground(new java.awt.Color(0, 0, 0));
        Lunes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lunes.setForeground(new java.awt.Color(255, 255, 255));
        Lunes.setText("Lunes");
        Lunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LunesActionPerformed(evt);
            }
        });
        getContentPane().add(Lunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 100, 30));

        Martes.setBackground(new java.awt.Color(0, 0, 0));
        Martes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Martes.setForeground(new java.awt.Color(255, 255, 255));
        Martes.setText("Martes");
        Martes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MartesActionPerformed(evt);
            }
        });
        getContentPane().add(Martes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 100, 30));

        Miercoles.setBackground(new java.awt.Color(0, 0, 0));
        Miercoles.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Miercoles.setForeground(new java.awt.Color(255, 255, 255));
        Miercoles.setText("Miercoles");
        Miercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiercolesActionPerformed(evt);
            }
        });
        getContentPane().add(Miercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 100, 30));

        Jueves.setBackground(new java.awt.Color(0, 0, 0));
        Jueves.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Jueves.setForeground(new java.awt.Color(255, 255, 255));
        Jueves.setText("Jueves");
        Jueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuevesActionPerformed(evt);
            }
        });
        getContentPane().add(Jueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 100, 30));

        Viernes.setBackground(new java.awt.Color(0, 0, 0));
        Viernes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Viernes.setForeground(new java.awt.Color(255, 255, 255));
        Viernes.setText("Viernes");
        Viernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViernesActionPerformed(evt);
            }
        });
        getContentPane().add(Viernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, 30));

        Sabado.setBackground(new java.awt.Color(0, 0, 0));
        Sabado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sabado.setForeground(new java.awt.Color(255, 255, 255));
        Sabado.setText("Sabado");
        Sabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SabadoActionPerformed(evt);
            }
        });
        getContentPane().add(Sabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 100, 30));

        Domingo.setBackground(new java.awt.Color(0, 0, 0));
        Domingo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Domingo.setForeground(new java.awt.Color(255, 255, 255));
        Domingo.setText("Domingo");
        Domingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomingoActionPerformed(evt);
            }
        });
        getContentPane().add(Domingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 100, 30));

        linea_azul.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/negroo.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout linea_azulLayout = new javax.swing.GroupLayout(linea_azul);
        linea_azul.setLayout(linea_azulLayout);
        linea_azulLayout.setHorizontalGroup(
            linea_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linea_azulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        linea_azulLayout.setVerticalGroup(
            linea_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linea_azulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(linea_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, -10, 10, 580));

        Salir.setBackground(new java.awt.Color(0, 0, 0));
        Salir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 120, -1));

        btn_Lavar_ya.setBackground(new java.awt.Color(0, 0, 0));
        btn_Lavar_ya.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_Lavar_ya.setForeground(new java.awt.Color(255, 255, 255));
        btn_Lavar_ya.setText("¡ Lavar Ya !");
        btn_Lavar_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Lavar_yaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Lavar_ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/negroo.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 820, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LunesActionPerformed
        // TODO add your handling code here:
        Lunes L = new Lunes();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LunesActionPerformed

    private void MartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MartesActionPerformed
        // TODO add your handling code here:
        Martes M = new Martes();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MartesActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void MiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiercolesActionPerformed
        // TODO add your handling code here:
        Miercoles Mi = new Miercoles();
        Mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MiercolesActionPerformed

    private void JuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuevesActionPerformed
        // TODO add your handling code here:
        Jueves J = new Jueves();
        J.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JuevesActionPerformed

    private void ViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViernesActionPerformed
        // TODO add your handling code here:
        Viernes V = new Viernes();
        V.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViernesActionPerformed

    private void SabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SabadoActionPerformed
        // TODO add your handling code here:
        Sabado S = new Sabado();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SabadoActionPerformed

    private void DomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomingoActionPerformed
        // TODO add your handling code here:
        Domingo D = new Domingo();
        D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DomingoActionPerformed

    private void btn_Lavar_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Lavar_yaActionPerformed
        // TODO add your handling code here:
        Lavar_Ya Y = new Lavar_Ya();
        Y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Lavar_yaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton Domingo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Icono;
    private javax.swing.JButton Jueves;
    private javax.swing.JButton Lunes;
    private javax.swing.JButton Martes;
    private javax.swing.JButton Miercoles;
    private javax.swing.JButton Sabado;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Viernes;
    private javax.swing.JButton btn_Lavar_ya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel linea_azul;
    // End of variables declaration//GEN-END:variables
}
